export const SEND_RESET_EMAIL_SUCCESS = "SEND_RESET_EMAIL_SUCCESS";
export const SEND_RESET_EMAIL_FAIL = "SEND_RESET_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD";
export const LOADING = "LOADING";
export const LOADING_ERROR = "LOADING_ERROR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR"
