export const REQUEST_USER_PROFILE_SUCCESS = "REQUEST_USER_PROFILE";
export const REQUEST_USER_PROFILE_FAILED = "REQUEST_USER_PROFILE_FAILED";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";
export const CHANGE_USER_PASSWORD_SUCCESS = "REQUEST_CHANGE_USER_PASSWORD";
export const CHANGE_USER_PASSWORD_FAILED = "REQUEST_CHANGE_USER_PASSWORD_FAILED";
export const LOADING = "LOADING";

