export const LOADING = "LOADING";

export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILED = "FETCH_USER_PROFILE_FAILED";

export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";

export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_FAILED = "CHANGE_USER_PASSWORD_FAILED";

export const FETCH_USER_PROFILE_LOADING = "FETCH_USER_PROFILE_LOADING";
export const CHANGE_USER_PASSWORD_LOADING = "CHANGE_USER_PASSWORD_LOADING";
export const UPDATE_USER_PROFILE_LOADING = "UPDATE_USER_PROFILE_LOADING";

export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";